import React from "react";

import type { TranslationReviewItem } from "../../../core/models";
import {
  addGlossaryFromOverride,
  getTranslationHistory,
  listTranslationReviewQueue,
  rejectAndRegenerateTranslation,
  approveTranslationForReview,
  editTranslationForReview,
  upsertTranslationMemoryCloudEntry,
} from "../../../core/services";

function formatTimestamp(timestamp: number): string {
  try {
    return new Date(timestamp).toLocaleString();
  } catch {
    return "Unknown";
  }
}

export function TranslationReviewPanel(): React.JSX.Element {
  const [language, setLanguage] = React.useState("all");
  const [subject, setSubject] = React.useState("");
  const [highlightZomi, setHighlightZomi] = React.useState(false);
  const [isLoading, setIsLoading] = React.useState(false);
  const [rows, setRows] = React.useState<TranslationReviewItem[]>([]);
  const [draftById, setDraftById] = React.useState<Record<string, string>>({});
  const [historyById, setHistoryById] = React.useState<Record<string, string>>({});
  const [statusMessage, setStatusMessage] = React.useState<string | null>(null);
  const [errorMessage, setErrorMessage] = React.useState<string | null>(null);

  const refreshQueue = React.useCallback(async (): Promise<void> => {
    setIsLoading(true);
    setErrorMessage(null);

    try {
      const queue = await listTranslationReviewQueue({
        language: language === "all" ? undefined : language,
        subject: subject || undefined,
        highlightZomi,
      });

      setRows(queue);
      setDraftById(Object.fromEntries(queue.map((entry) => [entry.id, entry.translatedText])));
      setStatusMessage(`Loaded ${queue.length} item${queue.length === 1 ? "" : "s"} for review.`);
    } catch {
      setErrorMessage("Unable to load translation review queue.");
    } finally {
      setIsLoading(false);
    }
  }, [highlightZomi, language, subject]);

  React.useEffect(() => {
    void refreshQueue();
  }, [refreshQueue]);

  async function handleApprove(item: TranslationReviewItem): Promise<void> {
    setErrorMessage(null);
    try {
      const updated = await approveTranslationForReview({
        language: item.language,
        termId: item.termId,
        actor: "admin",
      });

      if (!updated) {
        setErrorMessage("Translation not found.");
        return;
      }

      await upsertTranslationMemoryCloudEntry(updated, "shared");
      await refreshQueue();
      setStatusMessage("Translation approved and locked.");
    } catch {
      setErrorMessage("Unable to approve translation right now.");
    }
  }

  async function handleEdit(item: TranslationReviewItem): Promise<void> {
    setErrorMessage(null);
    const nextValue = draftById[item.id] ?? item.translatedText;

    try {
      const updated = await editTranslationForReview({
        language: item.language,
        termId: item.termId,
        sourceText: item.sourceText,
        translatedText: nextValue,
        actor: "admin",
      });

      await upsertTranslationMemoryCloudEntry(updated, "shared");
      await refreshQueue();
      setStatusMessage("Translation edited and synced to translation memory.");
    } catch {
      setErrorMessage("Unable to save edit right now.");
    }
  }

  async function handleRegenerate(item: TranslationReviewItem): Promise<void> {
    setErrorMessage(null);

    try {
      const regenerated = await rejectAndRegenerateTranslation({
        language: item.language,
        termId: item.termId,
        sourceText: item.sourceText,
        contextTags: item.contextTags,
      });

      await upsertTranslationMemoryCloudEntry(regenerated, "shared");
      await refreshQueue();
      setStatusMessage("Translation regenerated by AI and added back to queue.");
    } catch {
      setErrorMessage("Unable to regenerate translation right now.");
    }
  }

  async function handleViewHistory(item: TranslationReviewItem): Promise<void> {
    setErrorMessage(null);

    try {
      const history = await getTranslationHistory(item.language, item.termId);
      if (!history.length) {
        setHistoryById((previous) => ({
          ...previous,
          [item.id]: "No history recorded yet.",
        }));
        return;
      }

      const summary = history
        .slice(-5)
        .reverse()
        .map((entry) => `${formatTimestamp(entry.timestamp)} • ${entry.updatedBy}: \"${entry.oldValue}\" -> \"${entry.newValue}\"`)
        .join("\n");

      setHistoryById((previous) => ({
        ...previous,
        [item.id]: summary,
      }));
    } catch {
      setErrorMessage("Unable to load translation history.");
    }
  }

  async function handleAddToGlossary(item: TranslationReviewItem): Promise<void> {
    const subjectTag = item.contextTags[0] ?? "general";
    try {
      await addGlossaryFromOverride({
        subject: subjectTag,
        sourceLanguage: "en",
        targetLanguage: item.language,
        sourceTerm: item.sourceText,
        preferredTranslation: draftById[item.id] ?? item.translatedText,
        notes: `Added from translation review for ${item.termId}.`,
        usageRef: `translationMemory:${item.termId}`,
        actor: "admin",
      });
      setStatusMessage("Saved glossary term from translation override.");
    } catch {
      setErrorMessage("Unable to add glossary entry from this override.");
    }
  }

  return (
    <section className="admin-section" aria-live="polite">
      <div className="admin-section__header">
        <h3>Translation Review</h3>
        <button type="button" className="btn-secondary" onClick={() => { void refreshQueue(); }} disabled={isLoading}>
          {isLoading ? "Refreshing..." : "Refresh"}
        </button>
      </div>

      <p className="admin-note">Review AI and low-confidence translations. Approve, edit, or regenerate before classroom use.</p>

      <div className="admin-filter-bar">
        <label>
          Language
          <select value={language} onChange={(event) => setLanguage(event.target.value)}>
            <option value="all">All</option>
            <option value="en">en</option>
            <option value="es">es</option>
            <option value="pt">pt</option>
            <option value="fr">fr</option>
            <option value="de">de</option>
            <option value="zm">zm</option>
          </select>
        </label>

        <label>
          Subject Tag
          <input
            value={subject}
            onChange={(event) => setSubject(event.target.value.trim().toLowerCase())}
            placeholder="biology"
          />
        </label>

        <label>
          Highlight Zomi
          <select
            value={highlightZomi ? "yes" : "no"}
            onChange={(event) => setHighlightZomi(event.target.value === "yes")}
          >
            <option value="no">No</option>
            <option value="yes">Yes</option>
          </select>
        </label>

        <button type="button" className="btn-secondary" onClick={() => { void refreshQueue(); }}>
          Apply Filters
        </button>
      </div>

      {statusMessage ? <p className="admin-meta">{statusMessage}</p> : null}
      {errorMessage ? <p className="error-text">{errorMessage}</p> : null}

      {rows.length === 0 ? (
        <p className="admin-empty">No translation items currently require review.</p>
      ) : (
        <table className="admin-table">
          <thead>
            <tr>
              <th>Source Text</th>
              <th>Current Translation</th>
              <th>Language</th>
              <th>Confidence</th>
              <th>Context Tags</th>
              <th>Reason</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((item) => (
              <tr key={item.id}>
                <td>{item.sourceText}</td>
                <td>
                  <textarea
                    rows={2}
                    aria-label={`Edit translation for ${item.termId}`}
                    value={draftById[item.id] ?? item.translatedText}
                    onChange={(event) => {
                      const nextValue = event.target.value;
                      setDraftById((previous) => ({
                        ...previous,
                        [item.id]: nextValue,
                      }));
                    }}
                  />
                  {historyById[item.id] ? <pre className="admin-history">{historyById[item.id]}</pre> : null}
                </td>
                <td>{item.language.toUpperCase()}</td>
                <td>{Math.round(item.confidence * 100)}%</td>
                <td>{item.contextTags.join(", ") || "general"}</td>
                <td>{item.reason}</td>
                <td>
                  <div className="admin-premium-actions">
                    <button type="button" className="btn-secondary" onClick={() => { void handleApprove(item); }}>
                      Approve
                    </button>
                    <button type="button" className="btn-secondary" onClick={() => { void handleEdit(item); }}>
                      Edit
                    </button>
                    <button type="button" className="btn-secondary" onClick={() => { void handleRegenerate(item); }}>
                      Reject &amp; Regenerate
                    </button>
                    <button type="button" className="btn-secondary" onClick={() => { void handleViewHistory(item); }}>
                      View History
                    </button>
                    <button type="button" className="btn-secondary" onClick={() => { void handleAddToGlossary(item); }}>
                      Add to Glossary
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </section>
  );
}
